name: Auto Label Issues

on:
  issues:
    types: [opened, edited]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Label Issues
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const labelsToAdd = ["gssoc"];

            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: gssoc
            });
