name: Auto Greeting

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Add a greeting comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueComment = context.issue.number ? `Hi @${context.payload.issue.user.login},\n\nThanks for opening this issue! We appreciate your contribution and will get back to you as soon as possible.` : `Hi @${context.payload.pull_request.user.login},\n\nThanks for opening this pull request! We appreciate your contribution and will get back to you as soon as possible.`;
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: issueComment
            });
