name: Auto Greeting

on:
  issues:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet Contributor
        run: |
          echo "Hi there! Thanks for opening this issue. We appreciate your contribution and will look into it as soon as possible."
