name: Comment on New Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on New Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `
              👋 Hi there! Welcome to our repository! Thank you for your pull request. We appreciate your contribution.

              If you have any questions or need assistance, feel free to reach out to us on our Discord server: [Discord](https://discord.gg/rZb46cCMmK). We have created separate channels for all projects.

              Connect with us on social media:
              - **GitHub**: [GameSphere-MultiPlayer](https://github.com/GameSphere-MultiPlayer)
              - **LinkedIn**: [ChromeGaming](https://www.linkedin.com/company/chromegaming)
              - **Instagram**: [@chromegamingon](https://www.instagram.com/chromegamingon/)

              Happy coding! 🚀
              `
            });
            console.log(response);
