name: PR Auto Commenter

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Add a comment to the PR
      uses: actions-ecosystem/action-add-comment@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issue_number: ${{ github.event.pull_request.number }}
        body: |
          Thank you for your PR! Please ensure the following before we proceed:
          - [ ] All tests are passing
          - [ ] Code follows the project's style guidelines
          - [ ] Documentation has been updated if necessary
          - [ ] Changes are properly commented

          We appreciate your contribution!
