name: PR Commenter

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add PR Comment
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue_number = context.issue.number;
          const comment = `
          ### Automated PR Review

          Hello @${{ github.actor }},

          Thank you for your contribution! 🎉 Your pull request has been received and is under review. Here are a few preliminary checks and next steps:

          #### Preliminary Checks:
          - [x] PR title and description are clear and concise.
          - [x] All necessary labels have been applied.
          - [x] Associated issue number (if any) is mentioned.
          - [x] CI/CD checks are passing.

          #### Next Steps:
          1. **Code Review:** Your changes will be reviewed by the maintainers. They might request modifications or additional information.
          2. **Testing:** Ensure all tests pass and consider adding new tests if necessary.
          3. **Documentation:** Verify that any relevant documentation is updated.

          Thank you for your contribution! We look forward to reviewing your PR. 😊
          `;

          github.rest.issues.createComment({
            ...context.repo,
            issue_number,
            body: comment
          });
